export const CONFIG = {
  render: {
    pixelRatio: 1.25,
  },
  colors: {
    sky: 0x7aa2ff,
    ground: 0x7aa96b,
    track: 0x1d1f25,
    trackEmissive: 0x555555,
    edge: 0xffffff,
    ramp: 0x9a7b4f,
  },
  levels: [
    /* ── MUNDO 1: PRADERA ── */
    {
      key: "pradera-1", label: "¡Arrancamos!", world: "Pradera",
      groundColor: 0x7aa96b, skyColor: 0x7aa2ff, thumbColor: "#6ea85e",
      trackLength: 2040, obstacleCount: 2, rampCount: 1, treeCount: 8,
      collectible: { t: 0.5, lateral: 4.0 },
      turboPads: [], trampolines: [], lavaZones: [], mudZones: [],
      starZones: [{ t: 0.15, lateral: 3.5 }, { t: 0.5, lateral: -4.0 }], grayRamps: 0,
    },
    {
      key: "pradera-2", label: "Primer Charco", world: "Pradera",
      groundColor: 0x6fa05e, skyColor: 0x7aa2ff, thumbColor: "#5d9450",
      trackLength: 2120, obstacleCount: 3, rampCount: 1, treeCount: 10,
      collectible: { t: 0.35, lateral: -4.0 },
      turboPads: [], trampolines: [], lavaZones: [],
      mudZones: [{ t: 0.45, lateral: 0 }],
      starZones: [{ t: 0.14, lateral: -3.5 }, { t: 0.46, lateral: 3.2 }], grayRamps: 0,
    },
    {
      key: "pradera-3", label: "Turbo Bebé", world: "Pradera",
      groundColor: 0x83b56e, skyColor: 0x7aa2ff, thumbColor: "#72a45e",
      trackLength: 2180, obstacleCount: 3, rampCount: 1, treeCount: 10,
      collectible: { t: 0.6, lateral: 4.2 },
      turboPads: [{ t: 0.55, lateral: 0 }],
      trampolines: [], lavaZones: [], mudZones: [],
      starZones: [{ t: 0.15, lateral: 3.5 }, { t: 0.52, lateral: -3.3 }], grayRamps: 0,
    },
    {
      key: "pradera-4", label: "Salto de Fe", world: "Pradera",
      groundColor: 0x75a865, skyColor: 0x7aa2ff, thumbColor: "#649857",
      trackLength: 2240, obstacleCount: 3, rampCount: 2, treeCount: 12,
      collectible: { t: 0.4, lateral: -4.0 },
      turboPads: [], trampolines: [{ t: 0.65, lateral: 0 }],
      lavaZones: [], mudZones: [],
      starZones: [{ t: 0.18, lateral: -3.0 }, { t: 0.54, lateral: 2.6 }], grayRamps: 1,
    },
    {
      key: "pradera-5", label: "Lava Tímida", world: "Pradera",
      groundColor: 0x89b270, skyColor: 0x7aa2ff, thumbColor: "#78a060",
      trackLength: 2300, obstacleCount: 4, rampCount: 2, treeCount: 12,
      collectible: { t: 0.3, lateral: 4.0 },
      turboPads: [{ t: 0.5, lateral: 0 }],
      trampolines: [], lavaZones: [{ t: 0.8, lateral: 4.2 }],
      mudZones: [{ t: 0.25, lateral: 0 }],
      starZones: [{ t: 0.15, lateral: -3.0 }, { t: 0.47, lateral: 2.5 }], grayRamps: 1,
    },

    /* ── MUNDO 2: DESIERTO ── */
    {
      key: "desierto-1", label: "Dunas Doradas", world: "Desierto",
      groundColor: 0xc8a850, skyColor: 0xe8c87a, thumbColor: "#b89440",
      trackLength: 2440, obstacleCount: 4, rampCount: 2, treeCount: 6,
      collectible: { t: 0.45, lateral: -4.5 },
      turboPads: [], trampolines: [], lavaZones: [],
      mudZones: [{ t: 0.35, lateral: 0 }, { t: 0.65, lateral: 0 }],
      starZones: [{ t: 0.16, lateral: 4.0 }, { t: 0.45, lateral: -4.0 }], grayRamps: 1,
    },
    {
      key: "desierto-2", label: "Tormenta de Arena", world: "Desierto",
      groundColor: 0xd4a840, skyColor: 0xe8c87a, thumbColor: "#c09030",
      trackLength: 2500, obstacleCount: 5, rampCount: 2, treeCount: 6,
      collectible: { t: 0.55, lateral: 4.5 },
      turboPads: [{ t: 0.4, lateral: 0 }],
      trampolines: [{ t: 0.7, lateral: 0 }], lavaZones: [],
      mudZones: [{ t: 0.25, lateral: 0 }],
      starZones: [{ t: 0.13, lateral: -4.0 }, { t: 0.42, lateral: 3.7 }], grayRamps: 1,
    },
    {
      key: "desierto-3", label: "Oasis Turbinado", world: "Desierto",
      groundColor: 0xbe9c3e, skyColor: 0xe8c87a, thumbColor: "#a88830",
      trackLength: 2560, obstacleCount: 5, rampCount: 3, treeCount: 8,
      collectible: { t: 0.38, lateral: -4.5 },
      turboPads: [{ t: 0.45, lateral: 0 }, { t: 0.72, lateral: 0 }],
      trampolines: [], lavaZones: [],
      mudZones: [{ t: 0.3, lateral: 0 }],
      starZones: [{ t: 0.17, lateral: 3.5 }, { t: 0.5, lateral: -3.5 }], grayRamps: 1,
    },
    {
      key: "desierto-4", label: "El Gran Salto", world: "Desierto",
      groundColor: 0xc29238, skyColor: 0xe8c87a, thumbColor: "#ac7e28",
      trackLength: 2620, obstacleCount: 5, rampCount: 3, treeCount: 8,
      collectible: { t: 0.5, lateral: 4.5 },
      turboPads: [], trampolines: [{ t: 0.55, lateral: 0 }, { t: 0.8, lateral: 0 }],
      lavaZones: [], mudZones: [{ t: 0.35, lateral: 0 }],
      starZones: [{ t: 0.15, lateral: 4.0 }, { t: 0.45, lateral: -3.9 }], grayRamps: 1,
    },
    {
      key: "desierto-5", label: "Lava en el Desierto", world: "Desierto",
      groundColor: 0xb88830, skyColor: 0xe8c87a, thumbColor: "#a07020",
      trackLength: 2680, obstacleCount: 6, rampCount: 3, treeCount: 8,
      collectible: { t: 0.42, lateral: -4.5 },
      turboPads: [{ t: 0.6, lateral: 0 }],
      trampolines: [], lavaZones: [{ t: 0.78, lateral: -4.2 }, { t: 0.88, lateral: 4.2 }],
      mudZones: [{ t: 0.28, lateral: 0 }, { t: 0.5, lateral: 0 }],
      starZones: [{ t: 0.12, lateral: 3.5 }, { t: 0.53, lateral: -4.0 }], grayRamps: 2,
    },

    /* ── MUNDO 3: MONTAÑA ── */
    {
      key: "montana-1", label: "Camino Rocoso", world: "Montaña",
      groundColor: 0x8a7a6a, skyColor: 0x9ab8d0, thumbColor: "#7a6a5a",
      trackLength: 2760, obstacleCount: 5, rampCount: 3, treeCount: 14,
      collectible: { t: 0.47, lateral: 4.8 },
      turboPads: [{ t: 0.55, lateral: 0 }],
      trampolines: [{ t: 0.72, lateral: 0 }], lavaZones: [],
      mudZones: [{ t: 0.3, lateral: 0 }],
      starZones: [{ t: 0.14, lateral: -3.5 }, { t: 0.52, lateral: 3.7 }], grayRamps: 1,
    },
    {
      key: "montana-2", label: "Niebla y Barro", world: "Montaña",
      groundColor: 0x7a6e60, skyColor: 0x9ab8d0, thumbColor: "#6a5e50",
      trackLength: 2820, obstacleCount: 6, rampCount: 3, treeCount: 16,
      collectible: { t: 0.35, lateral: -4.8 },
      turboPads: [], trampolines: [], lavaZones: [],
      mudZones: [{ t: 0.28, lateral: 0 }, { t: 0.52, lateral: 0 }, { t: 0.72, lateral: 0 }],
      starZones: [{ t: 0.16, lateral: 4.0 }, { t: 0.46, lateral: -4.3 }], grayRamps: 1,
    },
    {
      key: "montana-3", label: "El Volcancito", world: "Montaña",
      groundColor: 0x906858, skyColor: 0x9ab8d0, thumbColor: "#7a5848",
      trackLength: 2820, obstacleCount: 6, rampCount: 3, treeCount: 14,
      collectible: { t: 0.42, lateral: 4.8 },
      turboPads: [{ t: 0.48, lateral: 0 }],
      trampolines: [{ t: 0.65, lateral: 0 }],
      lavaZones: [{ t: 0.82, lateral: 0 }],
      mudZones: [{ t: 0.3, lateral: 0 }],
      starZones: [{ t: 0.18, lateral: -3.5 }, { t: 0.54, lateral: 3.3 }], grayRamps: 2,
    },
    {
      key: "montana-4", label: "Turbos en la Cima", world: "Montaña",
      groundColor: 0x988070, skyColor: 0x9ab8d0, thumbColor: "#887060",
      trackLength: 2880, obstacleCount: 6, rampCount: 3, treeCount: 16,
      collectible: { t: 0.5, lateral: -4.8 },
      turboPads: [{ t: 0.42, lateral: 0 }, { t: 0.68, lateral: 0 }],
      trampolines: [], lavaZones: [{ t: 0.85, lateral: 4.5 }],
      mudZones: [{ t: 0.25, lateral: 0 }],
      starZones: [{ t: 0.15, lateral: 3.5 }, { t: 0.43, lateral: -3.9 }], grayRamps: 2,
    },
    {
      key: "montana-5", label: "Saltando a las Nubes", world: "Montaña",
      groundColor: 0xa08878, skyColor: 0x9ab8d0, thumbColor: "#907868",
      trackLength: 2940, obstacleCount: 6, rampCount: 4, treeCount: 16,
      collectible: { t: 0.38, lateral: 4.8 },
      turboPads: [{ t: 0.55, lateral: 0 }],
      trampolines: [{ t: 0.48, lateral: 0 }, { t: 0.78, lateral: 0 }],
      lavaZones: [{ t: 0.88, lateral: -4.5 }],
      mudZones: [{ t: 0.3, lateral: 0 }, { t: 0.62, lateral: 0 }],
      starZones: [{ t: 0.12, lateral: 3.5 }, { t: 0.53, lateral: -3.4 }], grayRamps: 2,
    },

    /* ── MUNDO 4: VOLCÁN ── */
    {
      key: "volcan-1", label: "Tierra en Llamas", world: "Volcán",
      groundColor: 0x7a3a20, skyColor: 0x4a1a0a, thumbColor: "#6a2a10",
      trackLength: 3000, obstacleCount: 6, rampCount: 3, treeCount: 10,
      collectible: { t: 0.45, lateral: -5.0 },
      turboPads: [{ t: 0.5, lateral: 0 }],
      trampolines: [], lavaZones: [{ t: 0.7, lateral: 4.5 }, { t: 0.88, lateral: -4.5 }],
      mudZones: [{ t: 0.3, lateral: 0 }],
      starZones: [{ t: 0.14, lateral: -4.0 }, { t: 0.52, lateral: 4.2 }], grayRamps: 2,
    },
    {
      key: "volcan-2", label: "Ríos de Lava", world: "Volcán",
      groundColor: 0x8a3c22, skyColor: 0x4a1a0a, thumbColor: "#7a2c12",
      trackLength: 3080, obstacleCount: 7, rampCount: 3, treeCount: 10,
      collectible: { t: 0.38, lateral: 5.0 },
      turboPads: [],
      trampolines: [{ t: 0.6, lateral: 0 }],
      lavaZones: [{ t: 0.5, lateral: 0 }, { t: 0.75, lateral: 4.5 }, { t: 0.88, lateral: -4.5 }],
      mudZones: [{ t: 0.28, lateral: 0 }],
      starZones: [{ t: 0.16, lateral: 4.0 }, { t: 0.49, lateral: -3.5 }], grayRamps: 2,
    },
    {
      key: "volcan-3", label: "¡Todo Turbo!", world: "Volcán",
      groundColor: 0x6e3018, skyColor: 0x4a1a0a, thumbColor: "#5e2008",
      trackLength: 3140, obstacleCount: 7, rampCount: 4, treeCount: 10,
      collectible: { t: 0.5, lateral: -5.0 },
      turboPads: [{ t: 0.38, lateral: 0 }, { t: 0.62, lateral: 0 }, { t: 0.82, lateral: 0 }],
      trampolines: [],
      lavaZones: [{ t: 0.72, lateral: 4.5 }, { t: 0.9, lateral: -4.5 }],
      mudZones: [],
      starZones: [{ t: 0.18, lateral: -3.5 }, { t: 0.47, lateral: 3.6 }], grayRamps: 2,
    },
    {
      key: "volcan-4", label: "El Infierno Saltarín", world: "Volcán",
      groundColor: 0x7c3418, skyColor: 0x4a1a0a, thumbColor: "#6c2808",
      trackLength: 3200, obstacleCount: 7, rampCount: 4, treeCount: 8,
      collectible: { t: 0.42, lateral: 5.0 },
      turboPads: [{ t: 0.45, lateral: 0 }],
      trampolines: [{ t: 0.55, lateral: 0 }, { t: 0.78, lateral: 0 }],
      lavaZones: [{ t: 0.65, lateral: 4.5 }, { t: 0.85, lateral: -4.5 }, { t: 0.93, lateral: 0 }],
      mudZones: [{ t: 0.28, lateral: 0 }],
      starZones: [{ t: 0.13, lateral: 4.0 }, { t: 0.53, lateral: -3.9 }], grayRamps: 2,
    },
    {
      key: "volcan-5", label: "El Jefe del Volcán", world: "Volcán",
      groundColor: 0x882a10, skyColor: 0x4a1a0a, thumbColor: "#781a00",
      trackLength: 3260, obstacleCount: 8, rampCount: 4, treeCount: 6,
      collectible: { t: 0.35, lateral: -5.0 },
      turboPads: [{ t: 0.4, lateral: 0 }, { t: 0.72, lateral: 0 }],
      trampolines: [{ t: 0.58, lateral: 0 }],
      lavaZones: [{ t: 0.68, lateral: 4.5 }, { t: 0.8, lateral: -4.5 }, { t: 0.88, lateral: 0 }, { t: 0.94, lateral: 4.5 }],
      mudZones: [],
      starZones: [{ t: 0.12, lateral: -4.0 }, { t: 0.25, lateral: 3.5 }], grayRamps: 3,
    },

    /* ── MUNDO 5: ÁRTICO ── */
    {
      key: "artico-1", label: "Nieve y Hielo", world: "Ártico",
      groundColor: 0xb8d4e8, skyColor: 0xd0e8f8, thumbColor: "#a8c4d8",
      trackLength: 3080, obstacleCount: 6, rampCount: 3, treeCount: 14,
      collectible: { t: 0.48, lateral: 5.0 },
      turboPads: [{ t: 0.55, lateral: 0 }],
      trampolines: [], lavaZones: [],
      mudZones: [{ t: 0.32, lateral: 0 }, { t: 0.65, lateral: 0 }],
      starZones: [{ t: 0.15, lateral: -4.0 }, { t: 0.53, lateral: 4.1 }], grayRamps: 2,
    },
    {
      key: "artico-2", label: "Ventisca", world: "Ártico",
      groundColor: 0xa8c8e0, skyColor: 0xd0e8f8, thumbColor: "#98b8d0",
      trackLength: 3200, obstacleCount: 7, rampCount: 3, treeCount: 16,
      collectible: { t: 0.38, lateral: -5.0 },
      turboPads: [], trampolines: [{ t: 0.6, lateral: 0 }],
      lavaZones: [], mudZones: [{ t: 0.28, lateral: 0 }, { t: 0.5, lateral: 0 }, { t: 0.72, lateral: 0 }],
      starZones: [{ t: 0.13, lateral: 4.0 }, { t: 0.51, lateral: -4.5 }], grayRamps: 2,
    },
    {
      key: "artico-3", label: "Salto del Oso Polar", world: "Ártico",
      groundColor: 0xc0d8ec, skyColor: 0xd0e8f8, thumbColor: "#b0c8dc",
      trackLength: 3260, obstacleCount: 7, rampCount: 4, treeCount: 16,
      collectible: { t: 0.45, lateral: 5.0 },
      turboPads: [{ t: 0.42, lateral: 0 }],
      trampolines: [{ t: 0.55, lateral: 0 }, { t: 0.8, lateral: 0 }],
      lavaZones: [], mudZones: [{ t: 0.3, lateral: 0 }, { t: 0.65, lateral: 0 }],
      starZones: [{ t: 0.17, lateral: -3.5 }, { t: 0.45, lateral: 3.3 }], grayRamps: 2,
    },
    {
      key: "artico-4", label: "La Tormenta Perfecta", world: "Ártico",
      groundColor: 0x98b8d5, skyColor: 0xd0e8f8, thumbColor: "#88a8c5",
      trackLength: 3400, obstacleCount: 8, rampCount: 4, treeCount: 18,
      collectible: { t: 0.4, lateral: -5.0 },
      turboPads: [{ t: 0.48, lateral: 0 }, { t: 0.74, lateral: 0 }],
      trampolines: [{ t: 0.62, lateral: 0 }],
      lavaZones: [], mudZones: [{ t: 0.28, lateral: 0 }, { t: 0.52, lateral: 0 }, { t: 0.7, lateral: 0 }],
      starZones: [{ t: 0.12, lateral: 4.0 }, { t: 0.43, lateral: -4.3 }], grayRamps: 3,
    },
    {
      key: "artico-5", label: "El Polo Sur Turbinado", world: "Ártico",
      groundColor: 0x88adc8, skyColor: 0xd0e8f8, thumbColor: "#789db8",
      trackLength: 3460, obstacleCount: 8, rampCount: 4, treeCount: 18,
      collectible: { t: 0.35, lateral: 5.0 },
      turboPads: [{ t: 0.4, lateral: 0 }, { t: 0.65, lateral: 0 }, { t: 0.85, lateral: 0 }],
      trampolines: [{ t: 0.52, lateral: 0 }, { t: 0.75, lateral: 0 }],
      lavaZones: [], mudZones: [{ t: 0.28, lateral: 0 }, { t: 0.58, lateral: 0 }],
      starZones: [{ t: 0.14, lateral: -4.0 }, { t: 0.22, lateral: 3.5 }], grayRamps: 3,
    },

    /* ── MUNDO 6: ESPACIO ── */
    {
      key: "espacio-1", label: "Despegue Lunar", world: "Espacio",
      groundColor: 0x3a3a5a, skyColor: 0x0a0a1e, thumbColor: "#2a2a4a",
      trackLength: 3200, obstacleCount: 6, rampCount: 3, treeCount: 6,
      collectible: { t: 0.5, lateral: -5.5 },
      turboPads: [{ t: 0.55, lateral: 0 }],
      trampolines: [{ t: 0.72, lateral: 0 }], lavaZones: [],
      mudZones: [],
      starZones: [{ t: 0.15, lateral: 4.0 }, { t: 0.43, lateral: -4.2 }], grayRamps: 2,
    },
    {
      key: "espacio-2", label: "Asteroide Salvaje", world: "Espacio",
      groundColor: 0x2e2e50, skyColor: 0x0a0a1e, thumbColor: "#1e1e40",
      trackLength: 3320, obstacleCount: 7, rampCount: 4, treeCount: 6,
      collectible: { t: 0.42, lateral: 5.5 },
      turboPads: [{ t: 0.45, lateral: 0 }, { t: 0.7, lateral: 0 }],
      trampolines: [{ t: 0.6, lateral: 0 }],
      lavaZones: [{ t: 0.85, lateral: 5.0 }], mudZones: [],
      starZones: [{ t: 0.13, lateral: -4.5 }, { t: 0.5, lateral: 4.4 }], grayRamps: 2,
    },
    {
      key: "espacio-3", label: "Caída Libre", world: "Espacio",
      groundColor: 0x1e1e3c, skyColor: 0x0a0a1e, thumbColor: "#0e0e2c",
      trackLength: 3460, obstacleCount: 7, rampCount: 4, treeCount: 4,
      collectible: { t: 0.38, lateral: -5.5 },
      turboPads: [{ t: 0.42, lateral: 0 }],
      trampolines: [{ t: 0.55, lateral: 0 }, { t: 0.78, lateral: 0 }],
      lavaZones: [{ t: 0.7, lateral: 5.0 }, { t: 0.88, lateral: -5.0 }],
      mudZones: [],
      starZones: [{ t: 0.16, lateral: 4.0 }, { t: 0.47, lateral: -4.3 }], grayRamps: 3,
    },
    {
      key: "espacio-4", label: "Galaxia en Llamas", world: "Espacio",
      groundColor: 0x28183c, skyColor: 0x0a0a1e, thumbColor: "#18082c",
      trackLength: 3520, obstacleCount: 8, rampCount: 4, treeCount: 4,
      collectible: { t: 0.45, lateral: 5.5 },
      turboPads: [{ t: 0.4, lateral: 0 }, { t: 0.65, lateral: 0 }],
      trampolines: [{ t: 0.52, lateral: 0 }],
      lavaZones: [{ t: 0.75, lateral: 0 }, { t: 0.85, lateral: 5.0 }, { t: 0.92, lateral: -5.0 }],
      mudZones: [],
      starZones: [{ t: 0.12, lateral: -4.5 }, { t: 0.22, lateral: 4.5 }], grayRamps: 3,
    },
    {
      key: "espacio-5", label: "El Jefe del Universo", world: "Espacio",
      groundColor: 0x1a0a2e, skyColor: 0x0a0a1e, thumbColor: "#0a001e",
      trackLength: 3840, obstacleCount: 8, rampCount: 4, treeCount: 4,
      collectible: { t: 0.35, lateral: -5.5 },
      turboPads: [{ t: 0.38, lateral: 0 }, { t: 0.58, lateral: 0 }, { t: 0.78, lateral: 0 }],
      trampolines: [{ t: 0.48, lateral: 0 }, { t: 0.7, lateral: 0 }],
      lavaZones: [{ t: 0.65, lateral: 5.0 }, { t: 0.8, lateral: -5.0 }, { t: 0.88, lateral: 0 }, { t: 0.94, lateral: 5.0 }],
      mudZones: [],
      starZones: [{ t: 0.1, lateral: -4.5 }, { t: 0.2, lateral: 4.5 }], grayRamps: 3,
    },

    /* ── MUNDO 7: SELVA ── */
    {
      key: "selva-1", label: "Bienvenido a la Jungla", world: "Selva",
      groundColor: 0x2d6b2e, skyColor: 0x4a8a30, thumbColor: "#1d5b1e",
      trackLength: 3900, obstacleCount: 5, rampCount: 3, treeCount: 22,
      collectible: { t: 0.5, lateral: 4.5 },
      turboPads: [{ t: 0.55, lateral: 0 }],
      trampolines: [], lavaZones: [],
      mudZones: [{ t: 0.3, lateral: 0 }, { t: 0.6, lateral: 0 }],
      starZones: [{ t: 0.15, lateral: -3.5 }, { t: 0.45, lateral: 3.9 }], grayRamps: 1,
    },
    {
      key: "selva-2", label: "Pantano Turbio", world: "Selva",
      groundColor: 0x3a7a2a, skyColor: 0x4a8a30, thumbColor: "#2a6a1a",
      trackLength: 3980, obstacleCount: 6, rampCount: 3, treeCount: 24,
      collectible: { t: 0.4, lateral: -4.5 },
      turboPads: [], trampolines: [{ t: 0.65, lateral: 0 }],
      lavaZones: [],
      mudZones: [{ t: 0.25, lateral: 0 }, { t: 0.48, lateral: 0 }, { t: 0.72, lateral: 0 }],
      starZones: [{ t: 0.13, lateral: 4.0 }, { t: 0.5, lateral: -3.9 }], grayRamps: 1,
    },
    {
      key: "selva-3", label: "Lianas y Turbos", world: "Selva",
      groundColor: 0x1e5a1e, skyColor: 0x4a8a30, thumbColor: "#0e4a0e",
      trackLength: 4060, obstacleCount: 6, rampCount: 4, treeCount: 26,
      collectible: { t: 0.45, lateral: 5.0 },
      turboPads: [{ t: 0.42, lateral: 0 }, { t: 0.7, lateral: 0 }],
      trampolines: [], lavaZones: [],
      mudZones: [{ t: 0.28, lateral: 0 }, { t: 0.55, lateral: 0 }],
      starZones: [{ t: 0.17, lateral: -4.0 }, { t: 0.44, lateral: 4.2 }], grayRamps: 2,
    },
    {
      key: "selva-4", label: "Cascada Mortal", world: "Selva",
      groundColor: 0x28682a, skyColor: 0x4a8a30, thumbColor: "#18581a",
      trackLength: 4140, obstacleCount: 7, rampCount: 4, treeCount: 28,
      collectible: { t: 0.38, lateral: -5.0 },
      turboPads: [{ t: 0.5, lateral: 0 }],
      trampolines: [{ t: 0.62, lateral: 0 }, { t: 0.82, lateral: 0 }],
      lavaZones: [{ t: 0.9, lateral: 4.5 }],
      mudZones: [{ t: 0.3, lateral: 0 }, { t: 0.65, lateral: 0 }],
      starZones: [{ t: 0.12, lateral: 3.5 }, { t: 0.44, lateral: -3.6 }], grayRamps: 2,
    },
    {
      key: "selva-5", label: "El Templo Perdido", world: "Selva",
      groundColor: 0x1a5420, skyColor: 0x4a8a30, thumbColor: "#0a4410",
      trackLength: 4300, obstacleCount: 8, rampCount: 4, treeCount: 30,
      collectible: { t: 0.35, lateral: 5.0 },
      turboPads: [{ t: 0.4, lateral: 0 }, { t: 0.68, lateral: 0 }],
      trampolines: [{ t: 0.55, lateral: 0 }],
      lavaZones: [{ t: 0.78, lateral: -4.5 }, { t: 0.92, lateral: 4.5 }],
      mudZones: [{ t: 0.25, lateral: 0 }, { t: 0.5, lateral: 0 }, { t: 0.72, lateral: 0 }],
      starZones: [{ t: 0.1, lateral: -4.0 }, { t: 0.2, lateral: 4.0 }], grayRamps: 3,
    },

    /* ── MUNDO 8: OCÉANO ── */
    {
      key: "oceano-1", label: "Aguas Tranquilas", world: "Océano",
      groundColor: 0x1a6080, skyColor: 0x2088b0, thumbColor: "#0a5070",
      trackLength: 4200, obstacleCount: 6, rampCount: 3, treeCount: 8,
      collectible: { t: 0.48, lateral: -5.0 },
      turboPads: [{ t: 0.52, lateral: 0 }],
      trampolines: [], lavaZones: [],
      mudZones: [{ t: 0.35, lateral: 0 }, { t: 0.68, lateral: 0 }],
      starZones: [{ t: 0.16, lateral: 4.0 }, { t: 0.55, lateral: -3.9 }], grayRamps: 2,
    },
    {
      key: "oceano-2", label: "Corriente Marina", world: "Océano",
      groundColor: 0x14527a, skyColor: 0x2088b0, thumbColor: "#04426a",
      trackLength: 4300, obstacleCount: 7, rampCount: 3, treeCount: 8,
      collectible: { t: 0.42, lateral: 5.0 },
      turboPads: [{ t: 0.45, lateral: 0 }, { t: 0.72, lateral: 0 }],
      trampolines: [{ t: 0.6, lateral: 0 }], lavaZones: [],
      mudZones: [{ t: 0.3, lateral: 0 }, { t: 0.55, lateral: 0 }],
      starZones: [{ t: 0.14, lateral: -4.5 }, { t: 0.49, lateral: 4.7 }], grayRamps: 2,
    },
    {
      key: "oceano-3", label: "Abismo Abisal", world: "Océano",
      groundColor: 0x0e4468, skyColor: 0x2088b0, thumbColor: "#003458",
      trackLength: 4400, obstacleCount: 7, rampCount: 4, treeCount: 6,
      collectible: { t: 0.38, lateral: -5.5 },
      turboPads: [{ t: 0.48, lateral: 0 }],
      trampolines: [{ t: 0.58, lateral: 0 }, { t: 0.8, lateral: 0 }],
      lavaZones: [{ t: 0.88, lateral: 5.0 }],
      mudZones: [{ t: 0.28, lateral: 0 }, { t: 0.62, lateral: 0 }],
      starZones: [{ t: 0.18, lateral: 3.5 }, { t: 0.53, lateral: -3.2 }], grayRamps: 2,
    },
    {
      key: "oceano-4", label: "Volcanes Submarinos", world: "Océano",
      groundColor: 0x0a3a5e, skyColor: 0x2088b0, thumbColor: "#002a4e",
      trackLength: 4500, obstacleCount: 8, rampCount: 4, treeCount: 6,
      collectible: { t: 0.45, lateral: 5.5 },
      turboPads: [{ t: 0.42, lateral: 0 }, { t: 0.7, lateral: 0 }],
      trampolines: [{ t: 0.55, lateral: 0 }],
      lavaZones: [{ t: 0.75, lateral: -5.0 }, { t: 0.9, lateral: 5.0 }],
      mudZones: [{ t: 0.3, lateral: 0 }, { t: 0.58, lateral: 0 }],
      starZones: [{ t: 0.12, lateral: -4.5 }, { t: 0.22, lateral: 4.0 }], grayRamps: 3,
    },
    {
      key: "oceano-5", label: "El Kraken", world: "Océano",
      groundColor: 0x062e50, skyColor: 0x2088b0, thumbColor: "#001e40",
      trackLength: 4600, obstacleCount: 8, rampCount: 4, treeCount: 4,
      collectible: { t: 0.35, lateral: -5.5 },
      turboPads: [{ t: 0.4, lateral: 0 }, { t: 0.62, lateral: 0 }, { t: 0.82, lateral: 0 }],
      trampolines: [{ t: 0.5, lateral: 0 }, { t: 0.72, lateral: 0 }],
      lavaZones: [{ t: 0.68, lateral: 5.0 }, { t: 0.85, lateral: -5.0 }, { t: 0.94, lateral: 0 }],
      mudZones: [{ t: 0.25, lateral: 0 }, { t: 0.55, lateral: 0 }],
      starZones: [{ t: 0.1, lateral: 4.5 }, { t: 0.2, lateral: -4.0 }], grayRamps: 3,
    },

    /* ── MUNDO 9: CIUDAD ── */
    {
      key: "ciudad-1", label: "Hora Punta", world: "Ciudad",
      groundColor: 0x505060, skyColor: 0x2a2a3a, thumbColor: "#404050",
      trackLength: 4500, obstacleCount: 7, rampCount: 4, treeCount: 10,
      collectible: { t: 0.5, lateral: 5.0 },
      turboPads: [{ t: 0.48, lateral: 0 }, { t: 0.72, lateral: 0 }],
      trampolines: [], lavaZones: [],
      mudZones: [{ t: 0.32, lateral: 0 }],
      starZones: [{ t: 0.15, lateral: -4.0 }, { t: 0.45, lateral: 3.5 }], grayRamps: 2,
    },
    {
      key: "ciudad-2", label: "Autopista Nocturna", world: "Ciudad",
      groundColor: 0x3e3e50, skyColor: 0x1a1a2e, thumbColor: "#2e2e40",
      trackLength: 4600, obstacleCount: 7, rampCount: 4, treeCount: 10,
      collectible: { t: 0.42, lateral: -5.0 },
      turboPads: [{ t: 0.45, lateral: 0 }, { t: 0.68, lateral: 0 }, { t: 0.85, lateral: 0 }],
      trampolines: [{ t: 0.6, lateral: 0 }], lavaZones: [],
      mudZones: [{ t: 0.28, lateral: 0 }, { t: 0.55, lateral: 0 }],
      starZones: [{ t: 0.13, lateral: 4.0 }, { t: 0.46, lateral: -4.2 }], grayRamps: 2,
    },
    {
      key: "ciudad-3", label: "Rascacielos Locos", world: "Ciudad",
      groundColor: 0x464658, skyColor: 0x2a2a3a, thumbColor: "#363648",
      trackLength: 4700, obstacleCount: 8, rampCount: 4, treeCount: 8,
      collectible: { t: 0.38, lateral: 5.5 },
      turboPads: [{ t: 0.5, lateral: 0 }],
      trampolines: [{ t: 0.55, lateral: 0 }, { t: 0.78, lateral: 0 }],
      lavaZones: [{ t: 0.88, lateral: 5.0 }],
      mudZones: [{ t: 0.3, lateral: 0 }],
      starZones: [{ t: 0.17, lateral: -3.5 }, { t: 0.45, lateral: 3.9 }], grayRamps: 3,
    },
    {
      key: "ciudad-4", label: "Zona de Obras", world: "Ciudad",
      groundColor: 0x585868, skyColor: 0x2a2a3a, thumbColor: "#484858",
      trackLength: 4800, obstacleCount: 8, rampCount: 4, treeCount: 8,
      collectible: { t: 0.45, lateral: -5.5 },
      turboPads: [{ t: 0.42, lateral: 0 }, { t: 0.7, lateral: 0 }],
      trampolines: [{ t: 0.52, lateral: 0 }],
      lavaZones: [{ t: 0.8, lateral: -5.0 }, { t: 0.92, lateral: 5.0 }],
      mudZones: [{ t: 0.28, lateral: 0 }, { t: 0.58, lateral: 0 }],
      starZones: [{ t: 0.12, lateral: 4.5 }, { t: 0.53, lateral: -4.7 }], grayRamps: 3,
    },
    {
      key: "ciudad-5", label: "Escape de la Ciudad", world: "Ciudad",
      groundColor: 0x2e2e40, skyColor: 0x1a1a2e, thumbColor: "#1e1e30",
      trackLength: 4900, obstacleCount: 9, rampCount: 4, treeCount: 6,
      collectible: { t: 0.35, lateral: 5.5 },
      turboPads: [{ t: 0.38, lateral: 0 }, { t: 0.6, lateral: 0 }, { t: 0.82, lateral: 0 }],
      trampolines: [{ t: 0.48, lateral: 0 }, { t: 0.72, lateral: 0 }],
      lavaZones: [{ t: 0.7, lateral: 5.0 }, { t: 0.85, lateral: -5.0 }, { t: 0.95, lateral: 0 }],
      mudZones: [{ t: 0.25, lateral: 0 }, { t: 0.52, lateral: 0 }],
      starZones: [{ t: 0.1, lateral: -4.5 }, { t: 0.2, lateral: 4.0 }], grayRamps: 3,
    },

    /* ── MUNDO 10: DULCE ── */
    {
      key: "dulce-1", label: "Valle de Caramelo", world: "Dulce",
      groundColor: 0xf0a0c0, skyColor: 0xffd0e8, thumbColor: "#e090b0",
      trackLength: 4800, obstacleCount: 7, rampCount: 4, treeCount: 14,
      collectible: { t: 0.48, lateral: -5.0 },
      turboPads: [{ t: 0.55, lateral: 0 }],
      trampolines: [{ t: 0.7, lateral: 0 }], lavaZones: [],
      mudZones: [{ t: 0.32, lateral: 0 }, { t: 0.62, lateral: 0 }],
      starZones: [{ t: 0.16, lateral: 4.0 }, { t: 0.51, lateral: -4.1 }], grayRamps: 2,
    },
    {
      key: "dulce-2", label: "Río de Chocolate", world: "Dulce",
      groundColor: 0xd888a8, skyColor: 0xffd0e8, thumbColor: "#c87898",
      trackLength: 4900, obstacleCount: 8, rampCount: 4, treeCount: 14,
      collectible: { t: 0.42, lateral: 5.0 },
      turboPads: [{ t: 0.45, lateral: 0 }, { t: 0.72, lateral: 0 }],
      trampolines: [], lavaZones: [],
      mudZones: [{ t: 0.28, lateral: 0 }, { t: 0.52, lateral: 0 }, { t: 0.75, lateral: 0 }],
      starZones: [{ t: 0.14, lateral: -3.5 }, { t: 0.54, lateral: 3.5 }], grayRamps: 2,
    },
    {
      key: "dulce-3", label: "Montaña de Gominolas", world: "Dulce",
      groundColor: 0xc070a0, skyColor: 0xffd0e8, thumbColor: "#b06090",
      trackLength: 5000, obstacleCount: 8, rampCount: 4, treeCount: 12,
      collectible: { t: 0.38, lateral: -5.5 },
      turboPads: [{ t: 0.5, lateral: 0 }],
      trampolines: [{ t: 0.58, lateral: 0 }, { t: 0.8, lateral: 0 }],
      lavaZones: [{ t: 0.9, lateral: 5.0 }],
      mudZones: [{ t: 0.3, lateral: 0 }, { t: 0.65, lateral: 0 }],
      starZones: [{ t: 0.18, lateral: 4.0 }, { t: 0.45, lateral: -4.3 }], grayRamps: 3,
    },
    {
      key: "dulce-4", label: "Piruletas Explosivas", world: "Dulce",
      groundColor: 0xb06098, skyColor: 0xffd0e8, thumbColor: "#a05088",
      trackLength: 5100, obstacleCount: 9, rampCount: 4, treeCount: 10,
      collectible: { t: 0.45, lateral: 5.5 },
      turboPads: [{ t: 0.42, lateral: 0 }, { t: 0.7, lateral: 0 }],
      trampolines: [{ t: 0.55, lateral: 0 }],
      lavaZones: [{ t: 0.78, lateral: -5.0 }, { t: 0.92, lateral: 5.0 }],
      mudZones: [{ t: 0.28, lateral: 0 }, { t: 0.58, lateral: 0 }],
      starZones: [{ t: 0.12, lateral: -4.5 }, { t: 0.22, lateral: 4.0 }], grayRamps: 3,
    },
    {
      key: "dulce-5", label: "El Rey del Azúcar", world: "Dulce",
      groundColor: 0x984888, skyColor: 0xffd0e8, thumbColor: "#883878",
      trackLength: 5200, obstacleCount: 9, rampCount: 4, treeCount: 8,
      collectible: { t: 0.35, lateral: -5.5 },
      turboPads: [{ t: 0.38, lateral: 0 }, { t: 0.6, lateral: 0 }, { t: 0.82, lateral: 0 }],
      trampolines: [{ t: 0.48, lateral: 0 }, { t: 0.72, lateral: 0 }],
      lavaZones: [{ t: 0.68, lateral: 5.0 }, { t: 0.85, lateral: -5.0 }, { t: 0.95, lateral: 0 }],
      mudZones: [{ t: 0.25, lateral: 0 }, { t: 0.52, lateral: 0 }],
      starZones: [{ t: 0.1, lateral: 4.5 }, { t: 0.2, lateral: -4.0 }], grayRamps: 3,
    },

    /* ── MUNDO 11: NUBES ── */
    {
      key: "nubes-1", label: "Primer Vuelo", world: "Nubes",
      groundColor: 0xd0e0f0, skyColor: 0xa0c8f0, thumbColor: "#c0d0e0",
      trackLength: 5100, obstacleCount: 7, rampCount: 4, treeCount: 6,
      collectible: { t: 0.5, lateral: 5.0 },
      turboPads: [{ t: 0.55, lateral: 0 }],
      trampolines: [{ t: 0.42, lateral: 0 }, { t: 0.7, lateral: 0 }],
      lavaZones: [], mudZones: [],
      starZones: [{ t: 0.15, lateral: -4.0 }, { t: 0.49, lateral: 3.8 }], grayRamps: 2,
    },
    {
      key: "nubes-2", label: "Arcoíris Turbo", world: "Nubes",
      groundColor: 0xc0d4e8, skyColor: 0xa0c8f0, thumbColor: "#b0c4d8",
      trackLength: 5200, obstacleCount: 8, rampCount: 4, treeCount: 6,
      collectible: { t: 0.42, lateral: -5.0 },
      turboPads: [{ t: 0.45, lateral: 0 }, { t: 0.68, lateral: 0 }, { t: 0.85, lateral: 0 }],
      trampolines: [{ t: 0.58, lateral: 0 }], lavaZones: [],
      mudZones: [{ t: 0.32, lateral: 0 }],
      starZones: [{ t: 0.13, lateral: 4.5 }, { t: 0.5, lateral: -4.1 }], grayRamps: 2,
    },
    {
      key: "nubes-3", label: "Tormenta Eléctrica", world: "Nubes",
      groundColor: 0x8898b0, skyColor: 0x607090, thumbColor: "#7888a0",
      trackLength: 5300, obstacleCount: 8, rampCount: 4, treeCount: 4,
      collectible: { t: 0.38, lateral: 5.5 },
      turboPads: [{ t: 0.5, lateral: 0 }],
      trampolines: [{ t: 0.55, lateral: 0 }, { t: 0.78, lateral: 0 }],
      lavaZones: [{ t: 0.88, lateral: -5.0 }],
      mudZones: [{ t: 0.3, lateral: 0 }, { t: 0.62, lateral: 0 }],
      starZones: [{ t: 0.17, lateral: -3.5 }, { t: 0.47, lateral: 3.2 }], grayRamps: 3,
    },
    {
      key: "nubes-4", label: "Salto entre Nubes", world: "Nubes",
      groundColor: 0xb0c8e0, skyColor: 0xa0c8f0, thumbColor: "#a0b8d0",
      trackLength: 5400, obstacleCount: 9, rampCount: 4, treeCount: 4,
      collectible: { t: 0.45, lateral: -5.5 },
      turboPads: [{ t: 0.42, lateral: 0 }, { t: 0.7, lateral: 0 }],
      trampolines: [{ t: 0.48, lateral: 0 }, { t: 0.65, lateral: 0 }, { t: 0.82, lateral: 0 }],
      lavaZones: [{ t: 0.9, lateral: 5.0 }],
      mudZones: [{ t: 0.28, lateral: 0 }],
      starZones: [{ t: 0.12, lateral: 4.5 }, { t: 0.22, lateral: -4.0 }], grayRamps: 3,
    },
    {
      key: "nubes-5", label: "El Cielo Final", world: "Nubes",
      groundColor: 0xe8f0f8, skyColor: 0xa0c8f0, thumbColor: "#d8e0f0",
      trackLength: 5500, obstacleCount: 9, rampCount: 4, treeCount: 4,
      collectible: { t: 0.35, lateral: 5.5 },
      turboPads: [{ t: 0.38, lateral: 0 }, { t: 0.6, lateral: 0 }, { t: 0.82, lateral: 0 }],
      trampolines: [{ t: 0.45, lateral: 0 }, { t: 0.68, lateral: 0 }, { t: 0.85, lateral: 0 }],
      lavaZones: [{ t: 0.75, lateral: -5.0 }, { t: 0.92, lateral: 5.0 }],
      mudZones: [],
      starZones: [{ t: 0.1, lateral: -4.5 }, { t: 0.2, lateral: 4.0 }], grayRamps: 3,
    },

    /* ── MUNDO 12: SUBTERRÁNEO ── */
    {
      key: "subterraneo-1", label: "Entrada a la Mina", world: "Subterráneo",
      groundColor: 0x4a3828, skyColor: 0x1a1008, thumbColor: "#3a2818",
      trackLength: 5400, obstacleCount: 8, rampCount: 4, treeCount: 8,
      collectible: { t: 0.48, lateral: -5.0 },
      turboPads: [{ t: 0.55, lateral: 0 }],
      trampolines: [{ t: 0.72, lateral: 0 }],
      lavaZones: [{ t: 0.85, lateral: 4.5 }],
      mudZones: [{ t: 0.3, lateral: 0 }, { t: 0.6, lateral: 0 }],
      starZones: [{ t: 0.16, lateral: 4.0 }, { t: 0.55, lateral: -4.0 }], grayRamps: 2,
    },
    {
      key: "subterraneo-2", label: "Caverna de Cristal", world: "Subterráneo",
      groundColor: 0x3a2a3c, skyColor: 0x1a0a1e, thumbColor: "#2a1a2c",
      trackLength: 5500, obstacleCount: 8, rampCount: 4, treeCount: 6,
      collectible: { t: 0.42, lateral: 5.0 },
      turboPads: [{ t: 0.45, lateral: 0 }, { t: 0.72, lateral: 0 }],
      trampolines: [{ t: 0.6, lateral: 0 }],
      lavaZones: [{ t: 0.8, lateral: -5.0 }, { t: 0.92, lateral: 5.0 }],
      mudZones: [{ t: 0.28, lateral: 0 }, { t: 0.55, lateral: 0 }],
      starZones: [{ t: 0.14, lateral: -4.0 }, { t: 0.43, lateral: 3.5 }], grayRamps: 3,
    },
    {
      key: "subterraneo-3", label: "Ríos de Magma", world: "Subterráneo",
      groundColor: 0x5a2a18, skyColor: 0x1a1008, thumbColor: "#4a1a08",
      trackLength: 5600, obstacleCount: 9, rampCount: 4, treeCount: 6,
      collectible: { t: 0.38, lateral: -5.5 },
      turboPads: [{ t: 0.48, lateral: 0 }],
      trampolines: [{ t: 0.55, lateral: 0 }, { t: 0.78, lateral: 0 }],
      lavaZones: [{ t: 0.68, lateral: 5.0 }, { t: 0.82, lateral: -5.0 }, { t: 0.92, lateral: 0 }],
      mudZones: [{ t: 0.3, lateral: 0 }],
      starZones: [{ t: 0.18, lateral: 4.0 }, { t: 0.43, lateral: -3.9 }], grayRamps: 3,
    },
    {
      key: "subterraneo-4", label: "Laberinto de Lava", world: "Subterráneo",
      groundColor: 0x482038, skyColor: 0x1a0a1e, thumbColor: "#381028",
      trackLength: 5800, obstacleCount: 9, rampCount: 4, treeCount: 4,
      collectible: { t: 0.45, lateral: 5.5 },
      turboPads: [{ t: 0.42, lateral: 0 }, { t: 0.68, lateral: 0 }],
      trampolines: [{ t: 0.52, lateral: 0 }, { t: 0.75, lateral: 0 }],
      lavaZones: [{ t: 0.62, lateral: 5.0 }, { t: 0.78, lateral: -5.0 }, { t: 0.88, lateral: 0 }, { t: 0.95, lateral: 5.0 }],
      mudZones: [{ t: 0.28, lateral: 0 }],
      starZones: [{ t: 0.12, lateral: -4.5 }, { t: 0.22, lateral: 4.0 }], grayRamps: 3,
    },
    {
      key: "subterraneo-5", label: "El Núcleo de la Tierra", world: "Subterráneo",
      groundColor: 0x3a0a1a, skyColor: 0x1a0008, thumbColor: "#2a000a",
      trackLength: 6000, obstacleCount: 10, rampCount: 4, treeCount: 4,
      collectible: { t: 0.35, lateral: -5.5 },
      turboPads: [{ t: 0.38, lateral: 0 }, { t: 0.58, lateral: 0 }, { t: 0.78, lateral: 0 }],
      trampolines: [{ t: 0.48, lateral: 0 }, { t: 0.68, lateral: 0 }, { t: 0.85, lateral: 0 }],
      lavaZones: [{ t: 0.55, lateral: 5.0 }, { t: 0.72, lateral: -5.0 }, { t: 0.82, lateral: 0 }, { t: 0.9, lateral: 5.0 }, { t: 0.96, lateral: -5.0 }],
      mudZones: [],
      starZones: [{ t: 0.1, lateral: 4.5 }, { t: 0.2, lateral: -4.5 }], grayRamps: 3,
    },
  ],
  track: {
    length: 800,
    segments: 200,
    halfWidth: 9,
    tailLength: 140,
    edgeOffset: 0.6,
    trackYOffset: 0.12,
    edgeYOffset: 0.18,
    curvatureMajor: Math.PI * 4,
    curvatureMinor: Math.PI * 1.5,
    curvatureMajorAmp: 12,
    curvatureMinorAmp: 6,
  },
  hud: {
    checkpoints: [0.25, 0.5, 0.75],
  },
  car: {
    halfX: 1.5,
    halfZ: 2.0,
    baseY: 0.05,
    wheelSpinMinRadius: 0.1,
  },
  physics: {
    accel: 22,
    reverseAccel: 18,
    drag: 0.975,
    maxSpeed: 41.7,
    maxReverse: 41.7,
    steerForce: 14,
    driftDrag: 2.4,
    curveForce: 0.0022,
    gravity: -28,
    speedToProgress: 0.0025,
    edgeSlowdown: 0.7,
    rampJumpSpeedMin: 4,
    rampJumpBoostSpeedFactor: 0.22,
    rampJumpBoostBase: 6.4,
  },
  obstacles: {
    layout: [
      { t: 0.18, lateral: -2.2, ramp: true },
      { t: 0.32, lateral: 2.4 },
      { t: 0.46, lateral: -1.8, ramp: true },
      { t: 0.58, lateral: 2.0 },
      { t: 0.7, lateral: -2.6, ramp: true },
      { t: 0.84, lateral: 2.2 },
    ],
    size: 2.4,
    height: 2.1,
    push: 1.4,
    reverse: 14,
    progressKick: 0.0015,
  },
  ramps: {
    frontWidth: 1.2,
    backWidth: 3.0,
    length: 4.4,
    height: 2.6,
    offsetT: 0.02,
  },
  trees: {
    count: 16,
    baseOffset: 6.5,
    width: 3.2,
    depth: 3.2,
    height: 6.5,
    jitter: 0.6,
    push: 2.2,
    reverse: 18,
    progressKick: 0.002,
    lateralDamping: 0.1,
  },
  collectible: {
    height: 1.5,
    rotateSpeed: 2.5,
  },
  turboPads: {
    width: 7.0,
    length: 5.0,
    boostSpeed: 56,
    boostDuration: 1.6,
    color: 0x00ffcc,
    emissiveIntensity: 1.3,
  },
  trampolines: {
    width: 8.0,
    length: 5.0,
    jumpVel: 28,
    color: 0xff7700,
  },
  lava: {
    width: 10.0,
    length: 8.0,
    color: 0xff2200,
    emissiveIntensity: 1.0,
  },
  mud: {
    width: 10.0,
    length: 10.0,
    maxSpeed: 7,
    color: 0x5c3d1e,
  },
  star: {
    width: 3.0,
    height: 2.0,
    duration: 10.0,
    rotateSpeed: 3.0,
    colorChangeInterval: 0.15,
  },
  grayRamps: {
    frontWidth: 1.6,
    backWidth: 3.5,
    length: 5.0,
    height: 2.8,
    offsetT: 0.015,
    color: 0x8a8a8a,
  },
  karts: [
    { file: "kart-oopi.glb", label: "Oopi", color: "#ff4444" },
    { file: "kart-oobi.glb", label: "Oobi", color: "#4488ff" },
    { file: "kart-oodi.glb", label: "Oodi", color: "#44dd44" },
    { file: "kart-ooli.glb", label: "Ooli", color: "#ff88ff" },
    { file: "kart-oozi.glb", label: "Oozi", color: "#ffaa22" },
  ],
  characters: [
    { id: "mario",      name: "Mario",       emoji: "🔴", vehicle: "kart",    color: "#e8231a", kart: "Standard Kart",  stats: { velocidad: 4, peso: 3, aceleracion: 3, manejo: 3 }, desc: "El fontanero más famoso. Todo terreno, para iniciados y expertos." },
    { id: "luigi",      name: "Luigi",       emoji: "💚", vehicle: "kart",    color: "#1e8c1e", kart: "Pipe Frame",     stats: { velocidad: 4, peso: 3, aceleracion: 4, manejo: 3 }, desc: "El hermano verde. Ligeramente más rápido en rectas largas." },
    { id: "peach",      name: "Peach",       emoji: "👑", vehicle: "mini",    color: "#ff88cc", kart: "Biddybuggy",    stats: { velocidad: 3, peso: 2, aceleracion: 5, manejo: 5 }, desc: "La princesa del Reino Champiñón. Pequeña, ágil, difícil de parar." },
    { id: "toad",       name: "Toad",        emoji: "🍄", vehicle: "mini",    color: "#4488ff", kart: "Biddybuggy",    stats: { velocidad: 3, peso: 1, aceleracion: 5, manejo: 5 }, desc: "El más ligero de todos. Aceleración brutal, domina las curvas." },
    { id: "yoshi",      name: "Yoshi",       emoji: "🦕", vehicle: "buggy",   color: "#44cc44", kart: "Wild Wiggler",  stats: { velocidad: 4, peso: 2, aceleracion: 4, manejo: 4 }, desc: "El dinosaurio amigo de Mario. Ligero, equilibrado y divertido." },
    { id: "wario",      name: "Wario",       emoji: "💛", vehicle: "dragster",color: "#ffcc00", kart: "Biddybuggy",    stats: { velocidad: 5, peso: 5, aceleracion: 2, manejo: 2 }, desc: "El antihéroe robusto. Devastador en rectas, pesado en curvas." },
    { id: "bowser",     name: "Bowser",       emoji: "🐢", vehicle: "monster", color: "#cc6600", kart: "Standard ATV", stats: { velocidad: 5, peso: 5, aceleracion: 2, manejo: 2 }, desc: "El rey de los Koopa. Velocidad máxima, manejo de experto." },
    { id: "rosalina",   name: "Rosalina",    emoji: "⭐", vehicle: "sports",  color: "#66aaff", kart: "Pipe Frame",    stats: { velocidad: 5, peso: 4, aceleracion: 3, manejo: 3 }, desc: "La guardiana de las estrellas. Elegante, veloz y precisa." },
    { id: "donkeykong", name: "Donkey Kong", emoji: "🦍", vehicle: "f1",      color: "#884400", kart: "Standard Kart", stats: { velocidad: 4, peso: 5, aceleracion: 3, manejo: 2 }, desc: "El rey del congo. Fuerza bruta y velocidad punta impresionante." },
    { id: "waluigi",    name: "Waluigi",     emoji: "🎭", vehicle: "f1",      color: "#880088", kart: "Wild Wiggler",  stats: { velocidad: 4, peso: 3, aceleracion: 4, manejo: 3 }, desc: "El rival estirado de Luigi. Ágil y con un estilo único." },
    { id: "koopa",      name: "Koopa",       emoji: "🐢", vehicle: "buggy",   color: "#88cc44", kart: "Biddybuggy",   stats: { velocidad: 3, peso: 2, aceleracion: 5, manejo: 5 }, desc: "El Koopa Troopa atleta. Ultraligero y con reflejos increíbles." },
    { id: "daisy",      name: "Daisy",       emoji: "🌼", vehicle: "mini",    color: "#ffaa00", kart: "Pipe Frame",    stats: { velocidad: 3, peso: 2, aceleracion: 5, manejo: 4 }, desc: "La princesa de Sarasa. Enérgica, competitiva e imprevisible." },
  ],
};
